[profile.release]
panic = "abort"
lto = true
#debug = true
#opt-level = 3
				   
[workspace]
members = [
    "bench",
    "infinitree",
    "infinitree-macros",
    "zerostash-files",
    "zerostash",
]
