[profile.release]
panic = "abort"
lto = true
# debug = true
# opt-level = 2
				   
[workspace]
members = [
    "bench",
    "infinitree",
    "infinitree-core",
    "infinitree-macros",
    "zerostash-files",
    "zerostash",
]
