[profile.release]
panic = "abort"
lto = true
debug = false
#opt-level = 1
				   
[workspace]
members = [
    "bench",
    "infinitree",
    "infinitree-macros",
    "zerostash-files",
    "zerostash",
]
