[package]
name = "zerostash"
authors = ["Peter Parkanyi <me@rhapsodhy.hu>"]
repository = "https://github.com/rsdy/zerostash"
license = "GPL-3.0"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.4"
infinitree = "0.3"
zerostash-files = { path = "../zerostash-files" }
num_cpus = "1.13.0"
rpassword = "5.0.0"
rprompt = "1.0.5"
serde = { version = "1", features = ["serde_derive"] }
toml = "0.5"
xdg = "2.2"

[dependencies.abscissa_tokio]
version = "=0.6.0-rc.0"

[dependencies.abscissa_core]
version = "=0.6.0-rc.0"

[dev-dependencies]
abscissa_core = { version = "0.6.0-rc.0", features = ["testing"] }
abscissa_tokio = { version = "0.6.0-rc.0" }
once_cell = "1.5"
