[package]
name = "zerostash"
description = "Safe and secure backup CLI"
authors = ["Peter Parkanyi <p@symmetree.dev>"]
repository = "https://github.com/symmetree-labs/zerostash"
license = "MIT/Apache-2.0"
version = "0.4.1"
edition = "2021"
keywords = ["crypto", "cli", "security", "filesystem", "backup"]
categories = ["cryptography", "filesystem", "command-line-utilities"]


[dependencies]
anyhow = "1.0.57"
thiserror = "1.0.31"
clap = "3.1.18"
infinitree = { version = "0.8.1" }
infinitree-backends = { path = "../../infinitree/infinitree-backends", default-features = false, features = ["rustls"] }
zerostash-files = { version = "0.4.1", path = "../zerostash-files" }
rpassword = "6.0.1"
rprompt = "1.0.5"
serde = { version = "1.0.137", features = ["serde_derive"] }
toml = "0.5.9"

dirs = "4.0.0"
xdg = "2.4.1"

async-trait = "0.1"
humansize = "1.1.1"
chrono = "0.4.19"
termcolor = "1.1.3"
nix = { version = "0.24.1", default-features = false, features = ["user"] }
abscissa_tokio= "0.6.0"
abscissa_core= "0.6.0"
regex = "1.5.6"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2.6.1"

[dev-dependencies]
abscissa_core = { version = "0.6.0", features = ["testing"] }
abscissa_tokio = "0.6.0"
walkdir = "2.3.2"
tokio = { version = "1.18.2", features = ["rt", "macros", "rt-multi-thread", "parking_lot"] }
num_cpus = "1.13.1"
tracing-subscriber = "0.3.11"
tracing = "0.1.34"


[[bench]]
name = "bench"
harness = false
path = "../bench/main.rs"
