[package]
name = "zerostash"
description = "Safe and secure backup CLI"
authors = ["Peter Parkanyi <p@symmetree.dev>"]
repository = "https://github.com/symmetree-labs/zerostash"
license = "MIT/Apache-2.0"
version = "0.4.0"
edition = "2021"
keywords = ["crypto", "cli", "security", "filesystem", "backup"]
categories = ["cryptography", "filesystem", "command-line-utilities"]


[dependencies]
anyhow = "1.0.57"
thiserror = "1.0.31"
clap = "3.1.18"
infinitree = { version = "0.8.0", default-features = false, features = ["rustls", "s3", "mmap"] }
zerostash-files = { version = "0.4.0", path = "../zerostash-files" }
num_cpus = "1.13.1"
rpassword = "6.0.1"
rprompt = "1.0.5"
serde = { version = "1.0.137", features = ["serde_derive"] }
toml = "0.5.9"
xdg = "2.4.1"
dirs = "4.0.0"
ignore = "0.4.18"

humansize = "1.1.1"
chrono = "0.4.19"
termcolor = "1.1.3"
nix = { version = "0.24.1", default-features = false, features = ["user"] }
abscissa_tokio= "0.6.0"
abscissa_core= "0.6.0"

[dev-dependencies]
abscissa_core = { version = "0.6.0", features = ["testing"] }
abscissa_tokio = "0.6.0"
once_cell = "1.12.0"
