[package]
name = "zerostash"
authors = ["Peter Parkanyi <p@symmetree.dev>"]
repository = "https://github.com/symmetree-labs/zerostash"
license = "GPL-3.0"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
clap = "3"
infinitree = { git = "https://github.com/symmetree-labs/infinitree" }
zerostash-files = { path = "../zerostash-files" }
num_cpus = "1.13.0"
rpassword = "5.0.0"
rprompt = "1.0.5"
serde = { version = "1", features = ["serde_derive"] }
toml = "0.5"
xdg = "2.2"
ignore = "0.4"

[dependencies.abscissa_tokio]
version = "0.6"

[dependencies.abscissa_core]
version = "0.6"

[dev-dependencies]
abscissa_core = { version = "0.6", features = ["testing"] }
abscissa_tokio = { version = "0.6" }
once_cell = "1.5"
