[package]
name = "zerostash"
authors = ["Peter Parkanyi <p@symmetree.dev>"]
repository = "https://github.com/symmetree-labs/zerostash"
license = "MIT/Apache-2.0"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
clap = "3"
infinitree = { version = "0.7", default-features = false, features=["rustls", "s3", "mmap"] }
zerostash-files = { version = "0.3", path = "../zerostash-files" }
num_cpus = "1.13.0"
rpassword = "6.0.0"
rprompt = "1.0.5"
serde = { version = "1", features = ["serde_derive"] }
toml = "0.5"
xdg = "2.2"
ignore = "0.4"

humansize = "1.1.1"
chrono = "0.4.19"
termcolor = "1.1"
nix = "0.24"

[dependencies.abscissa_tokio]
version = "0.6"

[dependencies.abscissa_core]
version = "0.6"

[dev-dependencies]
abscissa_core = { version = "0.6", features = ["testing"] }
abscissa_tokio = { version = "0.6" }
once_cell = "1.5"
