[package]
name = "zerostash"
description = "Safe and secure backup CLI"
authors = ["Peter Parkanyi <p@symmetree.dev>"]
repository = "https://github.com/symmetree-labs/zerostash"
license = "MIT/Apache-2.0"
version = "0.5.0"
edition = "2021"
keywords = ["crypto", "cli", "security", "filesystem", "backup"]
categories = ["cryptography", "filesystem", "command-line-utilities"]


[dependencies]
anyhow = "1.0.58"
thiserror = "1.0.31"
clap = "3.2.15"
infinitree = { version = "0.9.0", features = ["cryptobox", "yubikey"] }
infinitree-backends = { version = "0.9.0", default-features = false, features = ["rustls"] }
zerostash-files = { version = "0.5.0", path = "../zerostash-files" }
rpassword = "7.0.0"
rprompt = "1.0.5"
serde = { version = "1.0.140", features = ["serde_derive"] }
toml = "0.5.9"
bech32 = "0.9.0"

dirs = "4.0.0"
xdg = "2.4.1"

async-trait = "0.1.56"
humansize = "1.1.1"
chrono = { version = "0.4.19", default-features = false, features = ["std", "clock"] }
termcolor = "1.1.3"
nix = { version = "0.24.2", default-features = false, features = ["user"] }
abscissa_tokio= "0.6.0"
abscissa_core= "0.6.0"
regex = "1.6.0"

secrecy = { version = "0.8.0", features = ["serde"] }

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2.6.1"

[dev-dependencies]
abscissa_core = { version = "0.6.0", features = ["testing"] }
abscissa_tokio = "0.6.0"
walkdir = "2.3.2"
tokio = { version = "1.20.1", features = ["rt", "macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.15"
tracing = "0.1.35"


[[bench]]
name = "bench"
harness = false
path = "../bench/main.rs"
