[package]
name = "zerostash"
authors = ["Peter Parkanyi <me@rhapsodhy.hu>"]
repository = "https://github.com/rsdy/zerostash"
license = "GPL-3.0"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.2"
libzerostash = { path = "../libzerostash" }
num_cpus = "1.13.0"
rpassword = "5.0.0"
rprompt = "1.0.5"
serde = { version = "1", features = ["serde_derive"] }
toml = "0.5"
xdg = "2.2"

[dependencies.abscissa_tokio]
git = "https://github.com/rsdy/abscissa"
package = "abscissa_tokio"
branch = "main" 

[dependencies.abscissa_core]
git = "https://github.com/rsdy/abscissa"
package = "abscissa_core"
branch = "main" 

#version = "0.5.0"
# optional: use `gimli` to capture backtraces
# see https://github.com/rust-lang/backtrace-rs/issues/189
# features = ["gimli-backtrace"]

[dev-dependencies]
abscissa_core = { git = "https://github.com/rsdy/abscissa", package = "abscissa_core", features = ["testing"], branch = "main" }
abscissa_tokio = { git = "https://github.com/rsdy/abscissa", package = "abscissa_tokio", branch = "main" }
once_cell = "1.5"

