[package]
name = "zerostash-bench"
version = "0.1.0"
authors = ["Peter Parkanyi <me@rhapsodhy.hu>"]
repository = "https://github.com/rsdy/zerostash"
license = "GPL-3.0"
edition= "2018"

[dependencies]
libzerostash = { path = "../libzerostash" }
libzerostash-files = { path = "../libzerostash-files" }
walkdir = "^2.2.7"
tokio = { version = "^1", features = ["rt", "macros", "rt-multi-thread"] }
num_cpus = "1"

[dev-dependencies]
getrandom = "*"
memmap2 = "*"

[[bin]]
path = "src/main.rs"
name = "0s-bench"