[package]
name = "zerostash-files"
description = "Safe and secure backup library"
authors = ["Peter Parkanyi <p@symmetree.dev>"]
repository = "https://github.com/symmetree-labs/zerostash"
license = "MIT/Apache-2.0"
version = "0.4.1"
edition = "2021"
keywords = ["crypto", "api", "security", "filesystem", "backup"]
categories = ["cryptography", "filesystem"]

[dependencies]
infinitree = { git = "https://github.com/symmetree-labs/infinitree", default-features = false, features = ["rustls", "s3", "mmap"] }
serde = { version = "1.0.137", features = ["rc"] }
serde_derive = "1.0.137"
tracing = "0.1.34"
clap = { version = "3.1.18", features = ["derive"] }
anyhow = "1.0.57"
thiserror = "1.0.31"

memmap2 = "0.5.3"
glob = "0.3.0"
ignore = "0.4.18"

flume = "0.10.12"
futures = "0.3.21"
tokio = { version = "1.18.2", features = ["fs", "rt", "sync", "parking_lot"] }

itertools = "0.10.3"
seahash = "4.1.0"

libc = "0.2.126"
nix = { version = "0.24.1", default-features = false, features = ["fs"] }

chrono = "0.4.19"

[dev-dependencies]
getrandom = "0.2.6"
tokio = { version = "1.18.2", features = ["rt", "macros", "rt-multi-thread"] }
criterion = "0.3.5"
infinitree = { git = "https://github.com/symmetree-labs/infinitree", default-features = false, features = ["test", "s3", "mmap"] }

[[bench]]
name = "bench"
harness = false
path = "benches/bench.rs"
