[package]
name = "zerostash-files"
description = "Safe and secure backup library"
authors = ["Peter Parkanyi <p@symmetree.dev>"]
repository = "https://github.com/symmetree-labs/zerostash"
license = "MIT/Apache-2.0"
version = "0.4.1"
edition = "2021"
keywords = ["crypto", "api", "security", "filesystem", "backup"]
categories = ["cryptography", "filesystem"]

[dependencies]
infinitree = { version = "0.8.1", features = ["mmap"] }
serde = { version = "1.0.138", features = ["rc"] }
serde_derive = "1.0.138"
tracing = "0.1.35"
clap = { version = "3.2.8", features = ["derive"] }
anyhow = "1.0.58"
thiserror = "1.0.31"

memmap2 = "0.5.4"
glob = "0.3.0"
ignore = "0.4.18"

flume = "0.10.13"
futures = "0.3.21"
tokio = { version = "1.19.2", features = ["fs", "io-util", "rt", "sync", "parking_lot"] }

itertools = "0.10.3"
seahash = "4.1.0"

libc = "0.2.126"
nix = { version = "0.24.1", default-features = false, features = ["fs"] }

chrono = "0.4.19"

[dev-dependencies]
getrandom = "0.2.7"
tokio = { version = "1.19.2", features = ["rt", "macros", "rt-multi-thread"] }
criterion = "0.3.5"
infinitree = { version = "0.8.1", features = ["test"] }

[[bench]]
name = "bench"
harness = false
path = "benches/bench.rs"
