[package]
name = "zerostash-files"
description = "Safe and secure backup library"
authors = ["Peter Parkanyi <p@symmetree.dev>"]
repository = "https://github.com/symmetree-labs/zerostash"
license = "MIT/Apache-2.0"
version = "0.3.0"
edition = "2021"
keywords = ["crypto", "api", "security", "filesystem", "backup"]
categories = ["cryptography", "filesystem"]

[dependencies]
infinitree = { version = "0.7", default-features = false, features=["rustls", "s3", "mmap"] }
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
tracing = "0.1"
clap = "3"
anyhow = "1"
thiserror = "1"

memmap2 = "0.5"
glob = { version = "0.3" }
ignore = "^0.4"

flume = "^0.10"
futures = "0.3"
tokio = { version = "^1", features = ["fs", "rt", "sync", "parking_lot"] }

itertools = "0.10"
seahash = "4.0"

libc = "0.2"
nix = "0.24"

chrono = "0.4.19"

[dev-dependencies]
getrandom = "0.2"
tokio = { version = "^1", features = ["rt", "macros", "rt-multi-thread"] }
infinitree = { version = "0.6", default-features = false, features=["rustls", "s3", "mmap"] }