name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/<name>
            asset_name: <name>-linux

    steps:
    - uses: actions/checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: x86_64-unknown-linux-musl

    - name: Build
      uses: actions-rs/cargo@v1
      with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-musl

    - name: Upload binaries to release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}
