name: Quick check crates

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  clippy_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          components: clippy
          override: true
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  build:
    strategy:
      matrix:
        name: [
          linux,
          macos,
          macos-m1,
          windows
        ]

        include:
          - name: linux
            os: ubuntu-latest
            asset_name: 0s-linux-x86_64-static.tar.gz
            target: x86_64-unknown-linux-musl
            cross: true

          - name: macos
            os: macos-latest
            asset_name: 0s-macos-x86_64.tar.gz
            target: x86_64-apple-darwin
            cross: false

          - name: macos-m1
            os: macos-latest
            asset_name: 0s-macos-aarch64.tar.gz
            target: aarch64-apple-darwin
            cross: true

          - name: windows
            os: windows-latest
            asset_name: 0s-windows-x86_64.exe
            target: x86_64-pc-windows-msvc
            cross: false

        rust:
          - 1.61.0 # MSRV

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: ${{ matrix.target }}

      - name: Test
        if: matrix.target != 'aarch64-apple-darwin'
        uses: actions-rs/cargo@v1
        with:
            use-cross: ${{ matrix.cross }}
            args: --locked --target ${{ matrix.target }} --release
            command: test

      - name: Build
        uses: actions-rs/cargo@v1
        with:
            use-cross: ${{ matrix.cross }}
            args: --locked --target ${{ matrix.target }} --release
            command: build

      - name: Install
        uses: actions-rs/cargo@v1
        with:
            use-cross: ${{ matrix.cross }}
            args: --locked --target ${{ matrix.target }} --bin 0s --path zerostash --root output
            command: install

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: "output/bin/0s${{ matrix.os == 'windows-latest' && '.exe' || '' }}"

  package:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: bin

    - name: Package artifacts
      run: |
        set -e
        cd bin
        for dir in 0s-linux* 0s-macos*; do
          (cd $dir;
           echo $dir
           tar czf archive.tar.gz 0s;
           sha256sum archive.tar.gz
           rm 0s;
          )
        done

  release:
    runs-on: ubuntu-latest
    needs: [build, security_audit]
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: bin

    - name: Package artifacts
      run: |
        set -e
        cd bin
        for dir in 0s-linux* 0s-macos*; do
          (cd $dir;
           tar czf archive.tar.gz 0s;
           rm 0s;
          )
        done

    - name: Attach binaries to release
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs/promises');
          const path = require('path');

          const {owner, repo} = context.repo;
          const release_id = context.payload.release.id;

          const artifacts = await fs.readdir('bin/');

          for (dir of artifacts) {
              console.log(`Uploading ${dir}/0s for release ${release_id}`);

              const files = await fs.readdir(`bin/${dir}`);
              for (file of files) {
                  await github.rest.repos.uploadReleaseAsset({
                      owner,
                      repo,
                      release_id,
                      name: path.basename(dir),
                      data: await fs.readFile(`bin/${dir}/${file}`),
                  });

                  // only upload the first file
                  // there shouldn't be more anyway
                  break;
              }
          }
